### PR TITLE
Added main menu scene with working start and exit buttons

### PR DESCRIPTION
**Pull request by ghost**
image_2019-02-02_21-05-10

### CODE REVIEW

**Comment by UnoYakshi** [comment]
Why the hell I see the PR's notification?

**Comment by ghost** [comment]
@eadventurous ?

**Comment by e-ivkov** [comment]
> Why the hell I see the PR's notification?

I have no idea, you are not added to collaborators of this rep... Most probably because you are the owner of organization.

**Review by e-ivkov — COMMENTED** [review]
Everything is OK. I think we can merge.

**Pull request merged**
